set head off                                                                                                                                                                                                                                                                                                            
set lines 256                                                                                                                                                                                                                                                                                                           
set feedback off                                                                                                                                                                                                                                                                                                        
set pages 0                                                                                                                                                                                                                                                                                                             
spoo D:\import\UOM\BKLT.txt                                                                                                                                                                                                                                                                                             
select code || chr(9) || name || chr(9) || created_by || chr(9) || to_char(dt_created, 'DD-MON-YYYY') line_desc                                                                                                                                                                                                         
from inv_unit_of_measure                                                                                                                                                                                                                                                                                                
where code='BKLT'                                                                                                                                                                                                                                                                                                       
order by code;                                                                                                                                                                                                                                                                                                          
spoo off                                                                                                                                                                                                                                                                                                                
update inv_wsm_uoms set downloaded='Y', dt_downloaded=sysdate where uome_code = 'BKLT';                                                                                                                                                                                                                                 
commit;                                                                                                                                                                                                                                                                                                                 
@D:\systems\oracle\WSM\barcode_uoms.sql                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                        
