set head off                                                                                                                                                                                                                                                                                                            
set lines 256                                                                                                                                                                                                                                                                                                           
set feedback off                                                                                                                                                                                                                                                                                                        
set pages 0                                                                                                                                                                                                                                                                                                             
spoo D:\import\ITEM\MARI85_NAV_MARI_NAV-MARI.txt                                                                                                                                                                                                                                                                        
select itty_code || chr(9) || itgr_code || chr(9) || cate_code || chr(9) || code || chr(9) || '"' || GET_ITEM_DESC(code, cate_code, itty_code, itgr_code)  || '"' || chr(9) || tot_qty || chr(9) || bal_qty || chr(9) || uome_code line_desc                                                                            
from INV_ITEMS                                                                                                                                                                                                                                                                                                          
where code='MARI85'                                                                                                                                                                                                                                                                                                     
and   cate_code='NAV'                                                                                                                                                                                                                                                                                                   
and   itty_code='MARI'                                                                                                                                                                                                                                                                                                  
and   itgr_code='NAV-MARI'                                                                                                                                                                                                                                                                                              
order by code;                                                                                                                                                                                                                                                                                                          
spoo off                                                                                                                                                                                                                                                                                                                
update inv_wsm_items set downloaded='Y', dt_downloaded=sysdate where item_code = 'MARI85'                                                                                                                                                                                                                               
and   cate_code='NAV'                                                                                                                                                                                                                                                                                                   
and   itty_code='MARI'                                                                                                                                                                                                                                                                                                  
and   itgr_code='NAV-MARI';                                                                                                                                                                                                                                                                                             
commit;                                                                                                                                                                                                                                                                                                                 
@D:\systems\oracle\WSM\barcode_items.sql                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                        
