PROMPT Creating Sequence 'CADR_SEQ'
CREATE SEQUENCE CADR_SEQ
 NOMAXVALUE
 NOMINVALUE
 NOCYCLE
/

PROMPT Creating Table 'CMS_CATCHES_DR'
CREATE TABLE CMS_CATCHES_DR
 (TX_ID NUMBER NOT NULL
 ,TX_DATE DATE NOT NULL
 ,FR_VESS_CODE VARCHAR2(16) NOT NULL
 ,TO_VESS_CODE VARCHAR2(16) NOT NULL
 ,LUTO_QTY NUMBER(6) DEFAULT 0 NOT NULL
 ,STORAGE_QTY NUMBER(6) DEFAULT 0 NOT NULL
 ,DELIVERED_QTY NUMBER(6) DEFAULT 0 NOT NULL
 ,REMARKS VARCHAR2(256)
 ,CREATED_BY VARCHAR2(32) NOT NULL
 ,DT_CREATED DATE NOT NULL
 ,MODIFIED_BY VARCHAR2(32)
 ,DATE_MODIFIED DATE
 )
/

PROMPT Creating Table 'CMS_CATCHES_DR_DTLS'
CREATE TABLE CMS_CATCHES_DR_DTLS
 (CADR_TX_ID NUMBER NOT NULL
 ,TYFI_FISH VARCHAR2(16) NOT NULL
 ,TO_VESS_CODE VARCHAR2(16)
 ,FR_VESS_CODE VARCHAR2(16)
 ,TX_DATE DATE
 ,TOT_JMB NUMBER(8) DEFAULT 0 NOT NULL
 ,TOT_LRG NUMBER(8) DEFAULT 0 NOT NULL
 ,TOT_REG NUMBER(8) DEFAULT 0 NOT NULL
 ,TOT_MED NUMBER(8) DEFAULT 0 NOT NULL
 ,TOT_SML NUMBER(8) DEFAULT 0 NOT NULL
 ,REMARKS VARCHAR2(255)
 ,CREATED_BY VARCHAR2(32)
 ,DT_CREATED DATE
 ,MODIFIED_BY VARCHAR2(32)
 ,DT_MODIFIED DATE
 )
/

PROMPT Creating Primary Key on 'CMS_CATCHES_DR'
ALTER TABLE CMS_CATCHES_DR
 ADD (CONSTRAINT CADR_PK PRIMARY KEY 
  (TX_ID))
/

PROMPT Creating Primary Key on 'CMS_CATCHES_DR_DTLS'
ALTER TABLE CMS_CATCHES_DR_DTLS
 ADD (CONSTRAINT CDRD_PK PRIMARY KEY 
  (CADR_TX_ID
  ,TYFI_FISH))
/


   

PROMPT Creating Foreign Key on 'CMS_CATCHES_DR'
ALTER TABLE CMS_CATCHES_DR ADD (CONSTRAINT
 CADR_VESS_TO_FK FOREIGN KEY 
  (TO_VESS_CODE) REFERENCES CMS_VESSELS
  (CODE))
/

PROMPT Creating Foreign Key on 'CMS_CATCHES_DR'
ALTER TABLE CMS_CATCHES_DR ADD (CONSTRAINT
 CADR_VESS_FROM_FK FOREIGN KEY 
  (FR_VESS_CODE) REFERENCES CMS_VESSELS
  (CODE))
/

PROMPT Creating Foreign Key on 'CMS_CATCHES_DR_DTLS'
ALTER TABLE CMS_CATCHES_DR_DTLS ADD (CONSTRAINT
 CDRD_VESS_TO_FK FOREIGN KEY 
  (TO_VESS_CODE) REFERENCES CMS_VESSELS
  (CODE))
/

PROMPT Creating Foreign Key on 'CMS_CATCHES_DR_DTLS'
ALTER TABLE CMS_CATCHES_DR_DTLS ADD (CONSTRAINT
 CDRD_CADR_FK FOREIGN KEY 
  (CADR_TX_ID) REFERENCES CMS_CATCHES_DR
  (TX_ID))
/

PROMPT Creating Foreign Key on 'CMS_CATCHES_DR_DTLS'
ALTER TABLE CMS_CATCHES_DR_DTLS ADD (CONSTRAINT
 CDRD_VESS_FR_FK FOREIGN KEY 
  (FR_VESS_CODE) REFERENCES CMS_VESSELS
  (CODE))
/


