-- cdsddl.con
--
-- Generated for Oracle 9i on Tue Jan 16  23:07:46 2007 by Server Generator 6.5.96.5.6


ALTER TABLE CMS_VOYAGES DROP COLUMN LOCA_CODE
/

  
-- cdsddl.tab
--
-- Generated for Oracle 9i on Tue Jan 16  23:07:45 2007 by Server Generator 6.5.96.5.6
 

PROMPT Altering Table 'CMS_VOYAGES' 
ALTER TABLE CMS_VOYAGES 
 ADD (ORIGIN VARCHAR2(16) NOT NULL
 ,DESTINATION VARCHAR2(16) NOT NULL
 )
 MODIFY (EST_DEPARTURE date
 ,EST_ARRIVAL date
 ,DT_CREATED date
 ,DT_MODIFIED date
 )
/

PROMPT Altering Table 'CMS_CATCH_LOCATIONS' 
ALTER TABLE CMS_CATCH_LOCATIONS 
 MODIFY (DT_CREATED date
 ,DT_MODIFIED date
 )
/

PROMPT Altering Table 'CMS_VOYAGE_CREW' 
ALTER TABLE CMS_VOYAGE_CREW 
 MODIFY (PASSENGER VARCHAR2(1) DEFAULT 'N' NOT NULL
 ,DT_CREATED date
 ,DT_MODIFIED date
 )
/


PROMPT Creating Table 'CMS_VOYAGE_ROUTE'
CREATE TABLE CMS_VOYAGE_ROUTE
 (VOYA_VESS_CODE VARCHAR2(16) NOT NULL
 ,VOYA_VOYAGE_DATE DATE NOT NULL
 ,SEQ_NO NUMBER(4) NOT NULL
 ,ORIGIN VARCHAR2(16) NOT NULL
 ,DESTINATION VARCHAR2(16) NOT NULL
 ,ARRIVAL_DT DATE NOT NULL
 ,DEPARTURE_DT DATE NOT NULL
 ,CREATED_BY VARCHAR2(32) NOT NULL
 ,DT_CREATED date NOT NULL
 ,MODIFIED_BY VARCHAR2(32)
 ,DT_MODIFIED date
 )
/



PROMPT Creating Table 'CMS_CREW_ALLOWANCES'
CREATE TABLE CMS_CREW_ALLOWANCES
 (VOYA_VESS_CODE VARCHAR2(16) NOT NULL
 ,VOYA_VOYAGE_DATE DATE NOT NULL
 ,EMPL_EMPL_ID VARCHAR2(16) NOT NULL
 ,ALLO_CODE VARCHAR2(16) NOT NULL
 ,AMOUNT NUMBER(8,2) NOT NULL
 ,CREATED_BY VARCHAR2(32) NOT NULL
 ,DT_CREATED date NOT NULL
 ,MODIFIED_BY VARCHAR2(32)
 ,DT_MODIFIED date 
 )
/

PROMPT Creating Table 'PYS_EMPLOYEE_SALARY'
CREATE TABLE PYS_EMPLOYEE_SALARY
 (EMPL_EMPL_ID VARCHAR2(16) NOT NULL
 ,EFF_ST_DATE DATE NOT NULL
 ,EFF_EN_DATE DATE
 ,POSI_CODE VARCHAR2(16) NOT NULL
 ,DEPT_CODE VARCHAR2(16) NOT NULL
 ,BASIC_RATE NUMBER(8,2) DEFAULT 0 NOT NULL
 ,ALLOWANCES NUMBER(8,2) DEFAULT 0 NOT NULL
 ,CREATED_BY VARCHAR2(32) NOT NULL
 ,DT_CREATED DATE NOT NULL
 ,MODIFIED_BY VARCHAR2(32)
 ,DT_MODIFIED DATE
 )
/

PROMPT Creating Table 'PYS_EMPLOYEE_ALLOWANCES'
DROP TABLE PYS_EMPLOYEE_ALLOWANCES;
CREATE TABLE PYS_EMPLOYEE_ALLOWANCES
 (EMPL_EMPL_ID VARCHAR2(16) NOT NULL
 ,ALLO_CODE VARCHAR2(16) NOT NULL
 ,EFF_ST_DATE DATE NOT NULL
 ,EFF_EN_DATE DATE
 ,AMT NUMBER(7,2) NOT NULL
 ,CREATED_BY VARCHAR2(32) NOT NULL
 ,DT_CREATED DATE NOT NULL
 ,MODIFIED_BY VARCHAR2(32)
 ,DT_MODIFIED DATE
 )
/



PROMPT Creating Primary Key on 'CMS_VOYAGE_ROUTE'
ALTER TABLE CMS_VOYAGE_ROUTE
 ADD (CONSTRAINT VORO_PK PRIMARY KEY 
  (VOYA_VESS_CODE
  ,VOYA_VOYAGE_DATE
  ,SEQ_NO))
/

alter table pms_employees add sagr_code varchar2(16);


alter table pms_employees modify eff_st_date null;
    

PROMPT Creating Foreign Key on 'CMS_VOYAGES'
ALTER TABLE CMS_VOYAGES ADD (CONSTRAINT
 VOYA_LOCA_DEST_FK FOREIGN KEY 
  (DESTINATION) REFERENCES CMS_CATCH_LOCATIONS
  (CODE))
/

PROMPT Creating Foreign Key on 'CMS_VOYAGES'
ALTER TABLE CMS_VOYAGES ADD (CONSTRAINT
 VOYA_LOCA_ORIG_FK FOREIGN KEY 
  (ORIGIN) REFERENCES CMS_CATCH_LOCATIONS
  (CODE))
/

PROMPT Creating Foreign Key on 'CMS_VOYAGE_ROUTE'
ALTER TABLE CMS_VOYAGE_ROUTE ADD (CONSTRAINT
 VORO_LOCA_DEST_FK FOREIGN KEY 
  (DESTINATION) REFERENCES CMS_CATCH_LOCATIONS
  (CODE))
/

PROMPT Creating Foreign Key on 'CMS_VOYAGE_ROUTE'
ALTER TABLE CMS_VOYAGE_ROUTE ADD (CONSTRAINT
 VORO_LOCA_ORIG_FK FOREIGN KEY 
  (ORIGIN) REFERENCES CMS_CATCH_LOCATIONS
  (CODE))
/

PROMPT Creating Foreign Key on 'CMS_VOYAGE_ROUTE'
ALTER TABLE CMS_VOYAGE_ROUTE ADD (CONSTRAINT
 VORO_VOYA_FK FOREIGN KEY 
  (VOYA_VOYAGE_DATE
  ,VOYA_VESS_CODE) REFERENCES CMS_VOYAGES
  (VOYAGE_DATE
  ,VESS_CODE))
/


PROMPT Creating Primary Key on 'CMS_CREW_ALLOWANCES'
ALTER TABLE CMS_CREW_ALLOWANCES
 ADD (CONSTRAINT CRAL_PK PRIMARY KEY 
  (VOYA_VESS_CODE
  ,VOYA_VOYAGE_DATE
  ,EMPL_EMPL_ID
  ,ALLO_CODE))
/

PROMPT Creating Foreign Key on 'CMS_CREW_ALLOWANCES'
ALTER TABLE CMS_CREW_ALLOWANCES ADD (CONSTRAINT
 CRAL_EMPL_FK FOREIGN KEY 
  (EMPL_EMPL_ID) REFERENCES PMS_EMPLOYEES
  (EMPL_ID))
/

PROMPT Creating Foreign Key on 'CMS_CREW_ALLOWANCES'
ALTER TABLE CMS_CREW_ALLOWANCES ADD (CONSTRAINT
 CRAL_ALLO_FK FOREIGN KEY 
  (ALLO_CODE) REFERENCES PMS_ALLOWANCES
  (CODE))
/

PROMPT Creating Foreign Key on 'CMS_CREW_ALLOWANCES'
ALTER TABLE CMS_CREW_ALLOWANCES ADD (CONSTRAINT
 CRAL_VOYA_FK FOREIGN KEY 
  (VOYA_VOYAGE_DATE
  ,VOYA_VESS_CODE) REFERENCES CMS_VOYAGES
  (VOYAGE_DATE
  ,VESS_CODE))
/


PROMPT Creating Primary Key on 'PYS_EMPLOYEE_SALARY'
ALTER TABLE PYS_EMPLOYEE_SALARY
 ADD (CONSTRAINT EMSA_PK PRIMARY KEY 
  (EMPL_EMPL_ID
  ,EFF_ST_DATE))
/

PROMPT Creating Primary Key on 'PYS_EMPLOYEE_ALLOWANCES'
ALTER TABLE PYS_EMPLOYEE_ALLOWANCES
 ADD (CONSTRAINT EMAL_PK PRIMARY KEY 
  (EMPL_EMPL_ID
  ,ALLO_CODE
  ,EFF_ST_DATE))
/


    

PROMPT Creating Foreign Key on 'PYS_EMPLOYEE_SALARY'
ALTER TABLE PYS_EMPLOYEE_SALARY ADD (CONSTRAINT
 EMSA_EMPL_FK FOREIGN KEY 
  (EMPL_EMPL_ID) REFERENCES PMS_EMPLOYEES
  (EMPL_ID))
/

PROMPT Creating Foreign Key on 'PYS_EMPLOYEE_SALARY'
ALTER TABLE PYS_EMPLOYEE_SALARY ADD (CONSTRAINT
 EMSA_POSI_FK FOREIGN KEY 
  (POSI_CODE) REFERENCES PMS_POSITIONS
  (CODE))
/

PROMPT Creating Foreign Key on 'PYS_EMPLOYEE_SALARY'
ALTER TABLE PYS_EMPLOYEE_SALARY ADD (CONSTRAINT
 EMSA_DEPT_FK FOREIGN KEY 
  (DEPT_CODE) REFERENCES PMS_DEPARTMENTS
  (CODE))
/

PROMPT Creating Foreign Key on 'PYS_EMPLOYEE_ALLOWANCES'
ALTER TABLE PYS_EMPLOYEE_ALLOWANCES ADD (CONSTRAINT
 EMAL_EMSA_FK FOREIGN KEY 
  (EMPL_EMPL_ID
  ,EFF_ST_DATE) REFERENCES PYS_EMPLOYEE_SALARY
  (EMPL_EMPL_ID
  ,EFF_ST_DATE))
/

PROMPT Creating Foreign Key on 'PYS_EMPLOYEE_ALLOWANCES'
ALTER TABLE PYS_EMPLOYEE_ALLOWANCES ADD (CONSTRAINT
 EMAL_EMPL_FK FOREIGN KEY 
  (EMPL_EMPL_ID) REFERENCES PMS_EMPLOYEES
  (EMPL_ID))
/

PROMPT Creating Foreign Key on 'PYS_EMPLOYEE_ALLOWANCES'
ALTER TABLE PYS_EMPLOYEE_ALLOWANCES ADD (CONSTRAINT
 EMAL_ALLO_FK FOREIGN KEY 
  (ALLO_CODE) REFERENCES PMS_ALLOWANCES
  (CODE))
/

ALTER TABLE PMS_EMPLOYEES ADD (CONSTRAINT
 EMPL_SAGR_FK FOREIGN KEY 
  (SAGR_CODE) REFERENCES PMS_SALARY_GRADE
  (CODE))
/

PROMPT Creating Index 'EMAL_EMPL_FK_I'
CREATE INDEX EMAL_EMPL_FK_I ON PYS_EMPLOYEE_ALLOWANCES
 (EMPL_EMPL_ID)
/

PROMPT Creating Index 'EMAL_ALLO_FK_I'
CREATE INDEX EMAL_ALLO_FK_I ON PYS_EMPLOYEE_ALLOWANCES
 (ALLO_CODE)
/

