ALTER TABLE PMS_EMPLOYEES MODIFY HOME_TELNO NULL;
ALTER TABLE PMS_EMPLOYEES MODIFY SAGR_CODE NULL;
ALTER TABLE PMS_EMPLOYEES MODIFY EFF_ST_DATE NULL;
alter table PMS_EMPLOYMENT_HISTORIES modify JOB_DESCRIPTION null;
alter table PMS_EDUCATION_TRAININGS modify FIELD_COURSE null;
alter table pms_service_records modify REMARKS null;
