PROMPT Altering Table 'PMS_SERVICE_RECORDS' 
delete from PMS_SERVICE_RECORDS;
ALTER TABLE PMS_SERVICE_RECORDS 
 ADD (RANK_CODE VARCHAR2(16) NOT NULL
 )
/

PROMPT Creating Foreign Key on 'PMS_SERVICE_RECORDS'
ALTER TABLE PMS_SERVICE_RECORDS ADD (CONSTRAINT
 SERE_RANK_FK FOREIGN KEY 
  (RANK_CODE) REFERENCES PMS_RANKS
  (CODE))
/


