
CREATE TABLE TPJ.INV_RE_HDR
(
  RE_NO       VARCHAR2(16 BYTE)                NOT NULL,
  RE_TYPE     VARCHAR2(12 BYTE)                DEFAULT 'URS'                 NOT NULL,
  DT_RETURNED  DATE,
  RETURNED_BY  VARCHAR2(16 BYTE)                NOT NULL,
  PREPARED_BY  VARCHAR2(16 BYTE)                NOT NULL,
  DT_PREPARED  DATE,
  APPROVED_BY  VARCHAR2(16 BYTE),
  DT_APPROVED  DATE,
  STATUS       VARCHAR2(12 BYTE)                DEFAULT 'FOR APPROVAL',
  REMARKS      VARCHAR2(128 BYTE),
  CREATED_BY   VARCHAR2(32 BYTE)                NOT NULL,
  DT_CREATED   DATE                             NOT NULL,
  MODIFIED_BY  VARCHAR2(32 BYTE),
  DT_MODIFIED  DATE,
  CONSTRAINT REHD_PK
 PRIMARY KEY
 (RE_NO)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ),
  CONSTRAINT REHD_APOF_FK 
 FOREIGN KEY (APPROVED_BY) 
 REFERENCES TPJ.INV_APPROVING_OFFICER (CODE),  
  CONSTRAINT REHD_EMPL_FK 
 FOREIGN KEY (PREPARED_BY) 
 REFERENCES TPJ.PMS_EMPLOYEES (EMPL_ID),
 CONSTRAINT REHD_RETURN_FK 
 FOREIGN KEY (RETURNED_BY) 
 REFERENCES TPJ.PMS_EMPLOYEES (EMPL_ID)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );



CREATE TABLE TPJ.INV_RE_DTL
(
  REHD_RET_NO   VARCHAR2(16 BYTE)               NOT NULL,
  ITEM_NO       NUMBER(8),
  ISHD_ISS_NO   VARCHAR2(16 BYTE)               NOT NULL,
  RSHD_RS_NO    VARCHAR2(16 BYTE)               NOT NULL,  
  REF_TYPE      VARCHAR2(16 BYTE)               NOT NULL, -- STOCK OR DR
  DRHD_DR_NO    VARCHAR2(16 BYTE)               NOT NULL, -- WARECODE OR DR_NO
  POHD_PO_NO    VARCHAR2(16 BYTE)               ,  
  CATE_CODE     VARCHAR2(16 BYTE)               NOT NULL,
  ITTY_CODE     VARCHAR2(16 BYTE)               NOT NULL,
  ITGR_CODE     VARCHAR2(16 BYTE)               NOT NULL,
  ITEM_CODE     VARCHAR2(16 BYTE)               NOT NULL,
  UOME_CODE     VARCHAR2(16 BYTE)               NOT NULL,
  RETURNED_QTY  NUMBER(12,2)                    DEFAULT 0 NOT NULL,
  REMARKS       VARCHAR2(128 BYTE),
  CREATED_BY    VARCHAR2(32 BYTE)               NOT NULL,
  DT_CREATED    DATE                            NOT NULL,
  MODIFIED_BY   VARCHAR2(32 BYTE),
  DT_MODIFIED   DATE,
  CONSTRAINT REDT_PK
 PRIMARY KEY
 (REHD_RET_NO, ISHD_ISS_NO, ITEM_CODE, CATE_CODE, ITTY_CODE, ITGR_CODE, UOME_CODE)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       2147483645
                PCTINCREASE      0
               ),
  CONSTRAINT REDT_RTHD_FK 
 FOREIGN KEY (REHD_RET_NO) 
 REFERENCES TPJ.INV_RE_HDR (RE_NO)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );


DROP SEQUENCE TPJ.RE_SEQ;

CREATE SEQUENCE TPJ.RE_SEQ
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;


DROP PUBLIC SYNONYM RE_SEQ;

CREATE PUBLIC SYNONYM RE_SEQ FOR TPJ.RE_SEQ;


GRANT SELECT ON  TPJ.RE_SEQ TO TPJ_INV_SUPER_USER;

GRANT SELECT ON  TPJ.RE_SEQ TO TPJ_CMS_SUPER_USER;

GRANT SELECT ON  TPJ.RE_SEQ TO TPJ_PYS_SUPER_USER;

GRANT SELECT ON  TPJ.RE_SEQ TO TPJ_PMS_SUPER_USER;

GRANT SELECT ON  TPJ.RE_SEQ TO TPJ_PMS_MAINTENANCE_READ;

GRANT SELECT ON  TPJ.RE_SEQ TO TPJ_PMS_MAINTENANCE_WRITE;

GRANT SELECT ON  TPJ.RE_SEQ TO TPJ_PMS_APPLICANT_READ;

GRANT SELECT ON  TPJ.RE_SEQ TO TPJ_PMS_APPLICANT_WRITE;

GRANT SELECT ON  TPJ.RE_SEQ TO TPJ_PMS_EMPLOYEES_READ;

GRANT SELECT ON  TPJ.RE_SEQ TO TPJ_PMS_EMPLOYEES_WRITE;

GRANT SELECT ON  TPJ.RE_SEQ TO TPJ_PMS_LEAVES_READ;

GRANT SELECT ON  TPJ.RE_SEQ TO TPJ_PMS_LEAVES_WRITE;

GRANT SELECT ON  TPJ.RE_SEQ TO TPJ_PMS_VOYAGES_READ;

GRANT SELECT ON  TPJ.RE_SEQ TO TPJ_PMS_VOYAGES_WRITE;


INSERT INTO CG_REF_CODES (rv_domain, rv_meaning, rv_low_value) VALUES ('INV_RE_STATUS','FOR APPROVAL','For Approval');
INSERT INTO CG_REF_CODES (rv_domain, rv_meaning, rv_low_value) VALUES ('INV_RE_STATUS','NOTED','Noted');
INSERT INTO CG_REF_CODES (rv_domain, rv_meaning, rv_low_value) VALUES ('INV_RE_STATUS','APPROVED','Approved');
INSERT INTO CG_REF_CODES (rv_domain, rv_meaning, rv_low_value) VALUES ('INV_RE_STATUS','DISAPPROVED','Disapproved');
INSERT INTO CG_REF_CODES (rv_domain, rv_meaning, rv_low_value) VALUES ('INV_RE_STATUS','CANCELLED','Cancelled');

INSERT INTO CG_REF_CODES (rv_domain, rv_meaning, rv_low_value) VALUES ('INV_RE_TYPE', 'UIRS', 'Used Item RS');
INSERT INTO CG_REF_CODES (rv_domain, rv_meaning, rv_low_value) VALUES ('INV_RE_TYPE', 'TRS',  'Transfer RS');

