alter table ACC_PCV_HDR modify RECEIVED_BY varchar2(64);
alter table ACC_PCV_HDR add dt_prepared date;

alter table ACC_JV_HDR add (
      "CHECKED_BY" VARCHAR2(16),
      "DT_CHECKED" DATE
);

alter table ACC_JV_HDR modify (
      "PREPARED_BY" VARCHAR2(16)
);

CREATE TABLE "ACC_AP_HDR"
 (    "AP_NO" NUMBER(12,0) NOT NULL,
      "AP_DATE" DATE NOT NULL,
      "AP_STATUS" VARCHAR2(12) NOT NULL,
      "AP_PAYEE" VARCHAR2(64) NOT NULL,
      "AP_REF_NO" VARCHAR2(32) NOT NULL,
      "PREPARED_BY" VARCHAR2(16),
      "DT_PREPARED" DATE,
      "CHECKED_BY" VARCHAR2(16),
      "DT_CHECKED" DATE,
      "APPROVED_BY" VARCHAR2(16),
      "DT_APPROVED" DATE,
      "RECEIVED_BY" VARCHAR2(64),
      "DT_RECEIVED" DATE,
      "CREATED_BY" VARCHAR2(32) NOT NULL,
      "DT_CREATED" DATE NOT NULL,
      "MODIFIED_BY" VARCHAR2(32),
      "DT_MODIFIED" DATE,
       CONSTRAINT "APHD_PK" PRIMARY KEY ("AP_NO")
USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
TABLESPACE "USERS" 
 ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
TABLESPACE "USERS";

alter table ACC_AP_HDR add constraint APHD_EMPL_CHK_FK foreign key (CHECKED_BY)
references pms_employees (empl_id);
alter table ACC_AP_HDR add constraint APHD_EMPL_PREP_FK foreign key (PREPARED_BY)
references pms_employees (empl_id);
alter table ACC_AP_HDR add constraint APHD_APOF_FK foreign key (APPROVED_BY)
references inv_approving_officer (code);


CREATE TABLE "ACC_AP_DTL"
 (    "ITEM_NO" NUMBER(4,0) NOT NULL,
      "AP_NO" NUMBER(12,0) NOT NULL,
      "ACCO_CODE" VARCHAR2(22) NOT NULL,
      "REF_TYPE" VARCHAR2(16),
      "REF_CODE" VARCHAR2(32),
      "REF_DESC" VARCHAR2(256),
      "DEBIT" NUMBER(10,2) DEFAULT 0 NOT NULL,
      "CREDIT" NUMBER(10,2) DEFAULT 0 NOT NULL,
      "CREATED_BY" VARCHAR2(32) NOT NULL,
      "DT_CREATED" DATE NOT NULL,
      "MODIFIED_BY" VARCHAR2(32),
      "DT_MODIFIED" DATE,
       CONSTRAINT "APDT_PK" PRIMARY KEY ("AP_NO", "ITEM_NO")
USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
TABLESPACE "USERS" ,
       CONSTRAINT "APDT_APHD_FK" FOREIGN KEY ("AP_NO")
        REFERENCES "ACC_AP_HDR" ("AP_NO")
 ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
TABLESPACE "USERS";

alter table ACC_AP_DTL add constraint APDT_ACCO_FK foreign key (ACCO_CODE)
references acc_accounts (code);

ALTER TABLE ACC_AP_HDR 
 MODIFY (AP_STATUS  VARCHAR2(12) DEFAULT 'NEW'
 )
/

create sequence acc_ap_seq start with 1 increment by 1 nocache order;

DELETE FROM CG_REF_CODES
WHERE RV_DOMAIN = 'ACC_AP_HDR.AP_STATUS'
/

INSERT INTO CG_REF_CODES (RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING)
VALUES ('ACC_AP_HDR.AP_STATUS', 'NEW', NULL, NULL, 'New')
/
INSERT INTO CG_REF_CODES (RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING)
VALUES ('ACC_AP_HDR.AP_STATUS', 'NOTED', NULL, NULL, 'Noted')
/
INSERT INTO CG_REF_CODES (RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING)
VALUES ('ACC_AP_HDR.AP_STATUS', 'APPROVED', NULL, NULL, 'Approved')
/
INSERT INTO CG_REF_CODES (RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING)
VALUES ('ACC_AP_HDR.AP_STATUS', 'POSTED', NULL, NULL, 'Posted')
/
INSERT INTO CG_REF_CODES (RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING)
VALUES ('ACC_AP_HDR.AP_STATUS', 'CANCELLED', NULL, NULL, 'Cancelled')
/

COMMIT
/


DELETE FROM CG_REF_CODES
WHERE RV_DOMAIN = 'ACC_PCV_HDR.PCV_STATUS'
/

INSERT INTO CG_REF_CODES (RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING)
VALUES ('ACC_PCV_HDR.PCV_STATUS', 'NEW', NULL, NULL, 'New')
/
INSERT INTO CG_REF_CODES (RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING)
VALUES ('ACC_PCV_HDR.PCV_STATUS', 'APPROVED', NULL, NULL, 'Approved')
/
INSERT INTO CG_REF_CODES (RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING)
VALUES ('ACC_PCV_HDR.PCV_STATUS', 'POSTED', NULL, NULL, 'Posted')
/
INSERT INTO CG_REF_CODES (RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING)
VALUES ('ACC_PCV_HDR.PCV_STATUS', 'CANCELLED', NULL, NULL, 'Cancelled')
/

COMMIT
/


CREATE TABLE "ACC_AR_HDR"
 (    AR_NO NUMBER(12,0) NOT NULL,
      AR_DATE DATE NOT NULL,
      CUST_CODE VARCHAR2(16) NOT NULL,
      AR_STATUS VARCHAR2(12) DEFAULT 'NEW' NOT NULL,
      AR_PAYEE VARCHAR2(64) NOT NULL,
      AR_REF_NO VARCHAR2(32) NOT NULL,
      AR_AMT NUMBER(12,2) DEFAULT 0 NOT NULL,
      PREPARED_BY VARCHAR2(16),
      DT_PREPARED DATE,
      CHECKED_BY VARCHAR2(16),
      DT_CHECKED DATE,
      APPROVED_BY VARCHAR2(16),
      DT_APPROVED DATE,
      CREATED_BY VARCHAR2(32) NOT NULL,
      DT_CREATED DATE NOT NULL,
      MODIFIED_BY VARCHAR2(32),
      DT_MODIFIED DATE,
       CONSTRAINT ARHD_PK PRIMARY KEY (AR_NO)
);

ALTER TABLE ACC_AR_HDR ADD CONSTRAINT ARHD_CUST_FK FOREIGN KEY (CUST_CODE)
REFERENCES CMS_CUSTOMERS (CODE);



CREATE TABLE "ACC_AR_DTL"
 (    "ITEM_NO" NUMBER(4,0) NOT NULL,
      "AR_NO" NUMBER(12,0) NOT NULL,
      "ACCO_CODE" VARCHAR2(22) NOT NULL,
      "REF_TYPE" VARCHAR2(16),
      "REF_CODE" VARCHAR2(32),
      "REF_DESC" VARCHAR2(256),
      "DEBIT" NUMBER(10,2) DEFAULT 0 NOT NULL,
      "CREDIT" NUMBER(10,2) DEFAULT 0 NOT NULL,
      "CREATED_BY" VARCHAR2(32) NOT NULL,
      "DT_CREATED" DATE NOT NULL,
      "MODIFIED_BY" VARCHAR2(32),
      "DT_MODIFIED" DATE,
       CONSTRAINT "ARPDT_PK" PRIMARY KEY ("AR_NO", "ITEM_NO")
USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
TABLESPACE "USERS" ,
       CONSTRAINT "ARDT_ARHD_FK" FOREIGN KEY ("AR_NO")
        REFERENCES "ACC_AR_HDR" ("AR_NO")
 ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
STORAGE(INITIAL 65536 NEXT 65536 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
TABLESPACE "USERS";


create sequence acc_aR_seq start with 1 increment by 1 nocache order;

DELETE FROM CG_REF_CODES
WHERE RV_DOMAIN = 'ACC_AR_HDR.AR_STATUS'
/

INSERT INTO CG_REF_CODES (RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING)
VALUES ('ACC_AR_HDR.AR_STATUS', 'NEW', NULL, NULL, 'New')
/
INSERT INTO CG_REF_CODES (RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING)
VALUES ('ACC_AR_HDR.AR_STATUS', 'NOTED', NULL, NULL, 'Noted')
/
INSERT INTO CG_REF_CODES (RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING)
VALUES ('ACC_AR_HDR.AR_STATUS', 'APPROVED', NULL, NULL, 'Approved')
/
INSERT INTO CG_REF_CODES (RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING)
VALUES ('ACC_AR_HDR.AR_STATUS', 'CANCELLED', NULL, NULL, 'Cancelled')
/
INSERT INTO CG_REF_CODES (RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING)
VALUES ('ACC_AR_HDR.AR_STATUS', 'POSTED', NULL, NULL, 'Posted')
/

COMMIT
/


CREATE TABLE "ACC_CPA_HDR"
 (    CPA_NO NUMBER(12,0) NOT NULL,
      CPA_DATE DATE NOT NULL,
      CPA_STATUS VARCHAR2(12) DEFAULT 'NEW' NOT NULL,
      CPA_PAYEE VARCHAR2(64) NOT NULL,
      CPA_REF_NO VARCHAR2(32) NOT NULL,
      CPA_AMT NUMBER(12,2) DEFAULT 0 NOT NULL,
      PREPARED_BY VARCHAR2(16),
      DT_PREPARED DATE,
      CHECKED_BY VARCHAR2(16),
      DT_CHECKED DATE,
      APPROVED_BY VARCHAR2(16),
      DT_APPROVED DATE,
      CREATED_BY VARCHAR2(32) NOT NULL,
      DT_CREATED DATE NOT NULL,
      MODIFIED_BY VARCHAR2(32),
      DT_MODIFIED DATE,
       CONSTRAINT CPHD_PK PRIMARY KEY (CPA_NO)
);

alter table ACC_CPA_HDR add constraint CPHD_EMPL_CHK_FK foreign key (CHECKED_BY)
references pms_employees (empl_id);
alter table ACC_CPA_HDR add constraint CPHD_EMPL_PREP_FK foreign key (PREPARED_BY)
references pms_employees (empl_id);
alter table ACC_CPA_HDR add constraint CPHD_APOF_FK foreign key (APPROVED_BY)
references inv_approving_officer (code);
create sequence acc_cpa_seq start with 1 increment by 1 nocache order;

CREATE TABLE "ACC_CPA_DTL"
 (    "ITEM_NO" NUMBER(4,0) NOT NULL,
      "CPA_NO" NUMBER(12,0) NOT NULL,
      "ACCO_CODE" VARCHAR2(22) NOT NULL,
      "REF_TYPE" VARCHAR2(16),
      "REF_CODE" VARCHAR2(32),
      "REF_DESC" VARCHAR2(256),
      "DEBIT" NUMBER(10,2) DEFAULT 0 NOT NULL,
      "CREDIT" NUMBER(10,2) DEFAULT 0 NOT NULL,
      "CREATED_BY" VARCHAR2(32) NOT NULL,
      "DT_CREATED" DATE NOT NULL,
      "MODIFIED_BY" VARCHAR2(32),
      "DT_MODIFIED" DATE,
       CONSTRAINT "CPDT_PK" PRIMARY KEY ("CPA_NO", "ITEM_NO"),
       CONSTRAINT "CPDT_CPHD_FK" FOREIGN KEY ("CPA_NO")
        REFERENCES "ACC_CPA_HDR" ("CPA_NO")
 );

alter table ACC_CPA_DTL add constraint CPDT_ACCO_FK foreign key (ACCO_CODE)
references acc_accounts (code);

DELETE FROM CG_REF_CODES
WHERE RV_DOMAIN = 'ACC_CPA_HDR.CPA_STATUS'
/

INSERT INTO CG_REF_CODES (RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING)
VALUES ('ACC_CPA_HDR.CPA_STATUS', 'NEW', NULL, NULL, 'New')
/
INSERT INTO CG_REF_CODES (RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING)
VALUES ('ACC_CPA_HDR.CPA_STATUS', 'NOTED', NULL, NULL, 'Noted')
/
INSERT INTO CG_REF_CODES (RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING)
VALUES ('ACC_CPA_HDR.CPA_STATUS', 'APPROVED', NULL, NULL, 'Approved')
/
INSERT INTO CG_REF_CODES (RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING)
VALUES ('ACC_CPA_HDR.CPA_STATUS', 'CANCELLED', NULL, NULL, 'Cancelled')
/
INSERT INTO CG_REF_CODES (RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING)
VALUES ('ACC_CPA_HDR.CPA_STATUS', 'POSTED', NULL, NULL, 'Posted')
/

COMMIT
/


CREATE TABLE "ACC_CV_HDR"
 (    CV_NO NUMBER(12) NOT NULL,
      CV_DATE DATE NOT NULL,
      CV_STATUS VARCHAR2(12) DEFAULT 'NEW' NOT NULL,
      BANK_CODE VARCHAR2(16) NOT NULL,
      COMP_CODE VARCHAR2(16) NOT NULL,
      CPA_NO NUMBER(12) NOT NULL,
      CPA_AMT NUMBER(12,2) DEFAULT 0 NOT NULL,
      CPA_DATE DATE NOT NULL,
      CPA_PAYEE VARCHAR2(64) NOT NULL,
      CPA_REF_NO VARCHAR2(32) NOT NULL,
      ACCO_CODE  VARCHAR2(22),
      prnAcct_Desc  VARCHAR2(64),
      prnAcct_Amt   NUMBER(10,2),
      prnBank_Name  VARCHAR2(64),
      prnCheck_No   VARCHAR2(32),
      prnCheck_Date DATE,
      prnCheck_Amt  NUMBER(10,2),
      PREPARED_BY VARCHAR2(16),
      DT_PREPARED DATE,
      CHECKED_BY VARCHAR2(16),
      DT_CHECKED DATE,
      APPROVED_BY VARCHAR2(16),
      DT_APPROVED DATE,
      CREATED_BY VARCHAR2(32) NOT NULL,
      DT_CREATED DATE NOT NULL,
      MODIFIED_BY VARCHAR2(32),
      DT_MODIFIED DATE,
       CONSTRAINT CVHD_PK PRIMARY KEY (CV_NO)
);

alter table ACC_CV_HDR add constraint CVHD_EMPL_CHK_FK foreign key (CHECKED_BY)
references pms_employees (empl_id);
alter table ACC_CV_HDR add constraint CVHD_EMPL_PREP_FK foreign key (PREPARED_BY)
references pms_employees (empl_id);
alter table ACC_CV_HDR add constraint CVHD_APOF_FK foreign key (APPROVED_BY)
references inv_approving_officer (code);

alter table ACC_CV_HDR add constraint CVHD_ACCO_FK foreign key (ACCO_CODE)
references acc_accounts (code);
alter table ACC_CV_HDR add constraint CVHD_BANK_FK foreign key (BANK_CODE)
references acc_banks (code);
create sequence acc_cv_seq start with 1 increment by 1 nocache order;


CREATE TABLE "ACC_CV_DTL"
 (    "ITEM_NO" NUMBER(4,0) NOT NULL,
      "CV_NO" NUMBER(12,0) NOT NULL,
      "ACCO_CODE" VARCHAR2(22) NOT NULL,
      "REF_TYPE" VARCHAR2(16),
      "REF_CODE" VARCHAR2(32),
      "REF_DESC" VARCHAR2(256),
      "DEBIT" NUMBER(10,2) DEFAULT 0 NOT NULL,
      "CREDIT" NUMBER(10,2) DEFAULT 0 NOT NULL,
      "CREATED_BY" VARCHAR2(32) NOT NULL,
      "DT_CREATED" DATE NOT NULL,
      "MODIFIED_BY" VARCHAR2(32),
      "DT_MODIFIED" DATE,
       CONSTRAINT "CVDT_PK" PRIMARY KEY ("CV_NO", "ITEM_NO"),
       CONSTRAINT "CVDT_CVHD_FK" FOREIGN KEY ("CV_NO")
        REFERENCES "ACC_CV_HDR" ("CV_NO")
 );
 
alter table ACC_CV_DTL add constraint CVDT_ACCO_FK foreign key (ACCO_CODE)
references acc_accounts (code);

DELETE FROM CG_REF_CODES
WHERE RV_DOMAIN = 'ACC_CV_HDR.CV_STATUS'
/

INSERT INTO CG_REF_CODES (RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING)
VALUES ('ACC_CV_HDR.CV_STATUS', 'NEW', NULL, NULL, 'New')
/
INSERT INTO CG_REF_CODES (RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING)
VALUES ('ACC_CV_HDR.CV_STATUS', 'NOTED', NULL, NULL, 'Noted')
/
INSERT INTO CG_REF_CODES (RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING)
VALUES ('ACC_CV_HDR.CV_STATUS', 'APPROVED', NULL, NULL, 'Approved')
/
INSERT INTO CG_REF_CODES (RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING)
VALUES ('ACC_CV_HDR.CV_STATUS', 'CANCELLED', NULL, NULL, 'Cancelled')
/
INSERT INTO CG_REF_CODES (RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING)
VALUES ('ACC_CV_HDR.CV_STATUS', 'POSTED', NULL, NULL, 'Posted')
/

COMMIT
/

create public synonym ACC_CV_DTL for ACC_CV_DTL;
create public synonym ACC_CV_HDR for ACC_CV_HDR;
create public synonym ACC_CPA_DTL for ACC_CPA_DTL;
create public synonym ACC_CPA_HDR for ACC_CPA_HDR;
create public synonym ACC_CV_SEQ for ACC_CV_SEQ;
create public synonym ACC_CPA_SEQ for ACC_CPA_SEQ;

CREATE TABLE "ACC_PETTY_CASH"
(   "TX_DATE" DATE NOT NULL,
    "REF_TYPE" VARCHAR2(16),
    "REF_CODE" VARCHAR2(32),
    "REF_DESC" VARCHAR2(256),
    "AMT" NUMBER(10,2) DEFAULT 0 NOT NULL,
    "DEBIT" NUMBER(10,2) DEFAULT 0 NOT NULL,
    "CREDIT" NUMBER(10,2) DEFAULT 0 NOT NULL,
    "CREATED_BY" VARCHAR2(32) NOT NULL,
    "DT_CREATED" DATE NOT NULL,
    "MODIFIED_BY" VARCHAR2(32),
    "DT_MODIFIED" DATE,
     CONSTRAINT "PECA_PK" PRIMARY KEY ("TX_DATE", "REF_TYPE","REF_CODE")
);
create public synonym ACC_PETTY_CASH for ACC_PETTY_CASH;
grant select,update,delete,insert on ACC_PETTY_CASH to TPJ_ACC_SUPER_USER;

INSERT INTO ACC_SYSTEM_PARAMETERS values ('PETTY CASH', null, null, '10009', null);
commit;


alter table ACC_PCR_DTL add pcv_date date;
alter table ACC_PCR_HDR add beg_bal Number(12,2) default 0 not null;
alter table ACC_PCR_HDR add actual_cash_count Number(12,2) default 0 not null;
drop procedure sp_pc_replenishment;
drop public synonym sp_pc_replenishment;

INSERT INTO CG_REF_CODES (RV_DOMAIN, RV_LOW_VALUE, RV_HIGH_VALUE, RV_ABBREVIATION, RV_MEANING)
VALUES ('ACC_JV_HDR.JV_STATUS', 'NOTED', NULL, NULL, 'Noted')
/
commit;
