CREATE TABLE PYS_SSS_HEADER
 (    EFF_DATE DATE NOT NULL ENABLE,
      CREATED_BY VARCHAR2(32) NOT NULL ENABLE,
      DT_CREATED DATE NOT NULL ENABLE,
      MODIFIED_BY VARCHAR2(32),
      DT_MODIFIED DATE,
       CONSTRAINT SSHD_PK PRIMARY KEY (EFF_DATE)
USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
STORAGE(INITIAL 32768 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
TABLESPACE USERS  ENABLE
 ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
STORAGE(INITIAL 32768 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
TABLESPACE USERS
/

CREATE TABLE PYS_PHILHEALTH_HEADER
 (    EFF_DATE DATE NOT NULL ENABLE,
      CREATED_BY VARCHAR2(32) NOT NULL ENABLE,
      DT_CREATED DATE NOT NULL ENABLE,
      MODIFIED_BY VARCHAR2(32),
      DT_MODIFIED DATE,
       CONSTRAINT PHHD_PK PRIMARY KEY (EFF_DATE)
USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255
STORAGE(INITIAL 32768 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
TABLESPACE USERS  ENABLE
 ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
STORAGE(INITIAL 32768 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
TABLESPACE USERS
/

alter table PYS_PHILHEALTH_TABLE add eff_date date;
alter table PYS_SSS_TABLE add eff_date date;
   
update PYS_SSS_TABLE set eff_date = to_date('20010101','YYYYMMDD');
update PYS_PHILHEALTH_TABLE set eff_date = to_date('20010101','YYYYMMDD');

alter table PYS_SSS_TABLE modify eff_date not null;
alter table PYS_PHILHEALTH_TABLE modify eff_date not null;

alter table PYS_SSS_TABLE drop primary key;
alter table PYS_SSS_TABLE add constraint SSST_PK primary key (eff_date, salary_fr, salary_to);
alter table PYS_PHILHEALTH_TABLE modify eff_date not null;
alter table PYS_PHILHEALTH_TABLE drop primary key;
alter table PYS_PHILHEALTH_TABLE add constraint PHTA_PK primary key (eff_date, bracket);

create public synonym PYS_PHILHEALTH_HEADER for PYS_PHILHEALTH_HEADER;
create public synonym PYS_SSS_HEADER for PYS_SSS_HEADER;

grant select on PYS_SSS_HEADER to TPJ_PYS_SUPER_USER;
grant select on PYS_SSS_HEADER to TPJ_PYS_MAINTENANCE_READ;
grant select on PYS_SSS_HEADER to TPJ_PYS_MAINTENANCE_WRITE;
grant select on PYS_SSS_HEADER to TPJ_PYS_ATTENDANCE_READ;
grant select on PYS_SSS_HEADER to TPJ_PYS_ATTENDANCE_WRITE;
grant select on PYS_SSS_HEADER to TPJ_PYS_PAYROLL_READ;
grant select on PYS_SSS_HEADER to TPJ_PYS_PAYROLL_WRITE;
grant select on PYS_SSS_HEADER to TPJ_PYS_INCENTIVE_READ;
grant select on PYS_SSS_HEADER to TPJ_PYS_INCENTIVE_WRITE;
grant insert, update, delete on PYS_SSS_HEADER to TPJ_PYS_SUPER_USER;
grant insert, update, delete on PYS_SSS_HEADER to TPJ_PYS_MAINTENANCE_WRITE;
grant insert, update, delete on PYS_SSS_HEADER to TPJ_PYS_PAYROLL_WRITE;

grant select on PYS_PHILHEALTH_HEADER to TPJ_PYS_SUPER_USER;
grant select on PYS_PHILHEALTH_HEADER to TPJ_PYS_MAINTENANCE_READ;
grant select on PYS_PHILHEALTH_HEADER to TPJ_PYS_MAINTENANCE_WRITE;
grant select on PYS_PHILHEALTH_HEADER to TPJ_PYS_ATTENDANCE_READ;
grant select on PYS_PHILHEALTH_HEADER to TPJ_PYS_ATTENDANCE_WRITE;
grant select on PYS_PHILHEALTH_HEADER to TPJ_PYS_PAYROLL_READ;
grant select on PYS_PHILHEALTH_HEADER to TPJ_PYS_PAYROLL_WRITE;
grant select on PYS_PHILHEALTH_HEADER to TPJ_PYS_INCENTIVE_READ;
grant select on PYS_PHILHEALTH_HEADER to TPJ_PYS_INCENTIVE_WRITE;
grant insert, update, delete on PYS_PHILHEALTH_HEADER to TPJ_PYS_SUPER_USER;
grant insert, update, delete on PYS_PHILHEALTH_HEADER to TPJ_PYS_MAINTENANCE_WRITE;
grant insert, update, delete on PYS_PHILHEALTH_HEADER to TPJ_PYS_PAYROLL_WRITE;

insert into PYS_SSS_HEADER values (to_date('20010101', 'YYYYMMDD'), user, sysdate, null, null);
insert into PYS_PHILHEALTH_HEADER values (to_date('20010101', 'YYYYMMDD'), user, sysdate, null, null);
commit;

exec sp_recompute_13month (20081015, 20081031);

