ALTER TABLE PYS_PAYROLL_DTL ADD (
   OT_SU_PAY NUMBER(10,5) DEFAULT 0 NOT NULL,
   OT_HS_PAY NUMBER(10,5) DEFAULT 0 NOT NULL,
   A_OT_SU_PAY NUMBER(10,5) DEFAULT 0 NOT NULL,
   A_OT_HS_PAY NUMBER(10,5) DEFAULT 0 NOT NULL
);
